name 'learn_chef_httpd'
maintainer 'Kasun Rajapakse'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef_httpd'
long_description 'Installs/Configures learn_chef_httpd'
version '0.3.0'
