---
driver:
  name: azurerm

driver_config:
  subscription_id: 43b3f2ee-7c26-4ac9-b907-0fd7ce508380
  location: "Southeast Asia"
  machine_size: "Standard_D2"

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
      username: localadmin

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: